###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    # memcached:
    #     image: 'memcached:alpine'

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '8001:8025'

    redis:
        image: 'redis:alpine'

    postgres:
        image: 'postgres:13.3-alpine'
        container_name: postgres-database
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=oberon
        ports:
            - '8002:5432'
    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=adam.araujo.lima@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=PgAdmin2021!
        ports:
            - "5682:80"
        depends_on:
            - postgres

    # elasticsearch:
    #     image: 'elasticsearch:6.5.4'

    clickhouse:
        image: 'yandex/clickhouse-server:latest'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'
        depends_on: 
            - application

    application:
        build: phpdocker/php-fpm
        working_dir: /application
        container_name: application
        depends_on: 
            - postgres
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
        environment: 
            - DB_CONNECTION=pgsql
            - DB_HOST=postgres-database
            - DB_PORT=5432
            - DB_DATABASE=oberon
            - DB_USERNAME=admin
            - DB_PASSWORD=admin
