###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:

    redis:
        image: 'redis:alpine'

    postgres:
        image: 'postgres:13.3-alpine'
        container_name: postgres-database
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=oberon
        ports:
            - '8002:5432'
    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=adam.araujo.lima@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=PgAdmin2021!
        ports:
            - "5682:80"
        depends_on:
            - postgres

    webserver:
        image: 'nginx:alpine'
        working_dir: /oberon
        volumes:
            - './api:/oberon/api'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'
        depends_on: 
            - api

    api:
        build: api
        working_dir: /application
        container_name: api
        depends_on: 
            - postgres
        volumes:
            - './api:/oberon/api'
            - './api/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
        environment: 
            - DB_CONNECTION=pgsql
            - DB_HOST=postgres-database
            - DB_PORT=5432
            - DB_DATABASE=oberon
            - DB_USERNAME=admin
            - DB_PASSWORD=admin
    admin:
        image: node:latest
        working_dir: /application
        container_name: admin
        depends_on: 
            - api
        volumes:
            - './admin:/application'
            